apiVersion: v1
data:
    token: ENC[AES256_GCM,data:75GN7Gi9EW7AILTcABlyDA9yR+lkt/f7F4TR6sh+/+w07VH+aICcJwB/L+5e+825GPziXpQ0vj3oR0p/Q9S8/w==,iv:vMQNk/a3edni5tQdJ+DLBKGzCTVPON8XOuZBWNuw+Lg=,tag:PLTb8d40aQtnoUMYngK9Rg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-405517/locations/global/keyRings/sops-flux/cryptoKeys/sops-key-flux
          created_at: "2024-01-20T20:19:03Z"
          enc: CiQAiH4OjqUNQWlplIKpIvtqmnLJBPnZvx1mClPJssPQQoh6QjQSSQBHw5njZmolH1pwxKC5J9cQRQ65QnPdtoSVoIqq1MdvfGYC8DIWgypHaZVW5NO/CYHLh3aabBphEna+Bc35FaWpeJlxSF1OdF0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-20T20:19:03Z"
    mac: ENC[AES256_GCM,data:ZWcE03LKUy51sfrzb/UOlxjX1Kef6WnFFgV8PwA7En3AJJHrXp9J5D/bco8YwN3DQ1jyQqvEkdzwYgQCBLNPpyvqr3vw6pk0rye5NjUcd6BcsOHTk1L+Z29mgahRpR9t/BzpOJzO0Z3Oq1wDEB3DaupTbSkfruo2KxXSVODOrSU=,iv:+3gyKXY5yypsSJ2U2diyfW8HNDypWLrcSKR2/K4B4xI=,tag:VedeuGkGhc5y3S1jkHHQPw==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
